### ISSUE TITLE
El Capitan Support?

### ISSUE THREAD

**Issue by miralize** [tatey/Lighting#15]
I can see the toggle buttons very briefly when I open the notification centre, but they disappear almost instantly. Have you plans on updating it for El Capitan?

**Comment by tatey** [comment]
Hello!

Yes, I do plan to make this compatible with El Capitan and Yosemite. I need to update my machine first and I'm away for a wedding this weekend. Hopefully I'll be able to get this some time in the next couple of weeks. Obviously if someone else beats me to it I'll merge.

Cheers,
Tate

**Comment by tatey** [comment]
Good news. I've had a poke around and worked out what's going on. Grab the [1.1.3](https://github.com/tatey/Lighting/releases/tag/1.1.3) release which adds support for El Capitan.

It should continue to work fine on Yosemite as well, but I don't have a spare machine to test it on.

Anyway, give it a shot and let me know how you go.

**Comment by miralize** [comment]
I just tried it and unfortunately it didn't work.

So, I revoked my access token , generated a new one and now it wont even let me authenticate. It only says. 

"Invalid access token"

**Comment by lucymhdavies** [comment]
Hmm. Works fine for me on El Capitan.

**Comment by tatey** [comment]
Sorry @miralize. In trying to make it work with El Capitan I had broken login. Try grabbing [1.1.4](https://github.com/tatey/Lighting/releases/tag/1.1.4) and let me know how you go.

I'm noticing that the widget appears "frozen" after first installing. It's difficult to debug because I cannot reproduce it in the simulator. Logging and logging out of my user in OS X seems to get it into a good state again.

@lucymhdavies Glad to hear!

**Comment by tatey** [comment]
Getting reports from other people that this is working fine on El Capitan. It's also working for me. Closing.
